'use client';
import gsap from 'gsap';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { useEffect } from 'react';
import { ScrollSmoother } from '../lib/utils/gsap/ScrollSmoother';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	useEffect(() => {
		gsap.registerPlugin(ScrollTrigger, ScrollSmoother);
		const smoother = ScrollSmoother.create({
			smooth: 1,
			effects: true,
			smoothTouch: 0,
		});
	}, []);
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div id='smooth-wrapper' style={{ minWidth: '100vw' }}>
					{children}
				</div>
			</body>
		</html>
	);
}
